### ISSUE TITLE
Output of random graph generator (i.e. input of Dijkstra's)

### ISSUE THREAD

**Issue by xukai92** [xukai92/nndijkstra#1]
I will basically generate a text file with each line representing a graph, and will need you do run Dijkstra's on every graph (to output something). What kind of input do you want for your Dijkstra's algorithm? 

My current idea:

For each line of the data, representing a N * N adjacent matrix as

N a a a a a b b b b b c c c c c ...

Does it sound fine to you?

**Comment by yongli-abc** [comment]
OK. Sounds fine. Need to review Dijkstra's algorithm first. HEHE.

**Comment by xukai92** [comment]
HEHE good

**Comment by xukai92** [comment]
@NeilLi1992 do you remember whether directed or indirected graphs does Dijkstra's support?

**Comment by xukai92** [comment]
I've done a random graph generator - still some detail to discuss
1. We need set a meaningful maximum number of vertices - currently it's just 10.
2. The number of vertices `N` and the probability of setting an edge is now uniformly generated - maybe could use better distributions.

But anyway the sample graph seems to be fine for you to work on the Dijstra's. Please let me know there is anything you want me to change. @NeilLi1992

**Comment by xukai92** [comment]
Another issue of this random graph generator is that the generated graph is not fully connected - a lot of vertices is isolated. I'm looking into find another way to generate fully connected random graph.

**Comment by yongli-abc** [comment]
If the maximum number of vertices is only 10 at this stage, the different to use adjacency matrix vs list is ignorable.

Let's assume if you need to spawn a huge number of vertices, according to your way of setting the edge, do you expect the graph to be densely connected or sparsely connected?

If densely connected, (say for 10 nodes, we are having around 30-45 edges (assume undirected), then we go for adjacency matrix.

If sparsely connect, we go for adjacency list.

**Comment by yongli-abc** [comment]
@xukai92 I've checked and it seems Dijkstra algorithm supports directed graph with non-negative weights.

**Comment by xukai92** [comment]
@NeilLi1992 Are you sure? I found this from wiki

> Unlike Dijkstra's algorithm, the Bellman–Ford algorithm can be used on graphs with negative edge weights, as long as the graph contains no negative cycle reachable from the source vertex s.

This seems indicate that Dijkstra's doesn't support non-negative weights. But wiki may be wrong sometimes. Where did you get your conclusion from?

**Comment by yongli-abc** [comment]
@xukai92 According to your quotation, the Bellman-Ford algorithm can be used on 'negative weights', which means Dijkstra's algorithm can't be used on 'negative weights', so it can be used on 'non-negative weights'. What's the problem dude.

**Comment by xukai92** [comment]
@NeilLi1992 Sorry my bad. I misinterpreted your previous comment - I agree with that now.

But why did you mention that (suddenly) (again) - the motivation of this project is from the nature that Dijstra's **only** support non-negative weights. (see `README.md`)

And for the previous question about dense v.s. sparse. I guess it doesn't matter too much in our project - but I fell dense graphs would be more easier form NN to capture the Dijstra's algorithm. So I would say we will have dense graphs with <= 50 nodes.

**Comment by yongli-abc** [comment]
OK, then will go for adjacency matrix.
Haven't really looked through the README file, sorry hehe. Just had a quick revision of Dijkstra algorithm.

Quite busy these days, looking for new place to rent, totally exhausted. Maybe I'll have some time for coding tomorrow. Hope so.

**Comment by xukai92** [comment]
Don't worry. Just take your time - this project is not urgent at all. I'm also very busy and didn't work on it these days - gonna have a meeting with Zoubin tomorrow but don't any result to show hehe.

Good luck with your house moving. :)

**Comment by yongli-abc** [comment]
N a a a a a b b b b b c c c c c ...

BTW, in your example, N should be 5, and each following number is the edge weight, right?

**Comment by xukai92** [comment]
Yeah. BTW I will re-write the random graph generator (RGG) in Python, making our source codes consistent and fix bugs.

**Comment by xukai92** [comment]
@NeilLi1992 Which Python version are you using?

**Comment by xukai92** [comment]
@NeilLi1992 Alive?

**Comment by xukai92** [comment]
We have an updated version of the random graph generator.
